feat: new tx filter format
neutron-org/neutron-contracts pull request #15
Opened 2022-08-19 13:56 UTC by ratik

now cosmos relayer supports new format for [tx filter](https://p2pvalidator.atlassian.net/jira/software/projects/LSC/boards/121?selectedIssue=LSC-121) so the interchain queries contract was updated
Testing tips: 
1. neutron from master
2. cosmos-query-relayer from [feature/new-transaction-filter](https://github.com/neutron-org/cosmos-query-relayer/pull/26)

2022-08-22 09:05 UTC, pr0n00gler commented on packages/interchain_queries/src/register_queries.rs
> +        field: "transfer.recipient".to_string(),
Define a constant, please

2022-08-22 09:05 UTC, pr0n00gler commented on packages/interchain_queries/src/sudo.rs
> +                    if row.field == "transfer.address" && row.op.as_str() == "eq" {
`"transfer.address"`? Don't we need a `"transfer.recipient"` here?

2022-08-22 09:21 UTC, swelf19 commented on packages/interchain_queries/src/sudo.rs
> +                    if row.field == "transfer.address" && row.op.as_str() == "eq" {
You can derive PartialEq and Eq traits with a `TransactionFilterOp` definition and compare row.op with a TransactionFilterOp::Eq not a str

2022-08-22 09:21 UTC, swelf19 commented on packages/interchain_queries/src/sudo.rs
> +                let recipient = query_data.iter().fold("", |prev, row| {
don't you think find(+map) looks simpler at this place?

2022-08-22 19:14 UTC, ratik commented
sorry guys, had to rebase it bc some refactoring merged before this PR

2022-08-23 06:37 UTC, swelf19 approved these changes

2022-08-23 14:06 UTC, sotnikov-s requested changes
I think it would be very useful if you added the complicated query support to the neutron_interchain_queries contract, cuz now it only accepts the recipient and inside constructs a simple query `transfer.recipient == recipient`. here's why:
1. I'd like to test it with a complicated query, but currently it's impossible;
2. in integration tests it is also a crucial thing.

2022-08-24 08:58 UTC, ratik commented
> I think it would be very useful if you added the complicated query support to the neutron_interchain_queries contract, cuz now it only accepts the recipient and inside constructs a simple query `transfer.recipient == recipient`. here's why:
> 
> 1. I'd like to test it with a complicated query, but currently it's impossible;
> 2. in integration tests it is also a crucial thing.
> 
> so please add this functionality and update test_tx_query_result.sh accordingly

agreed with @sotnikov-s that we need add one more RegisterTransfersQuery but with filtering by height

2022-08-24 10:16 UTC, oopcode approved these changes
tested with `test_tx_query_result.sh`

2022-08-25 08:04 UTC, ratik commented on packages/interchain_queries/src/types.rs
> +}
Please pay attention here

2022-08-25 08:05 UTC, ratik commented on packages/interchain_queries/src/types.rs
> +}
@oopcode

2022-08-25 10:07 UTC, oopcode approved these changes
tested with `test_tx_query_result.sh`, everything seems to work fine now

2022-08-25 11:43 UTC, sotnikov-s approved these changes

2022-08-25 12:40 UTC, oopcode approved these changes

2022-08-25 12:41 UTC, merged