feat: added ibc responses
neutron-org/neutron-contracts pull request #25
Opened 2022-09-09 07:53 UTC by swelf19

2022-09-10 21:10 UTC, oopcode commented on contracts/neutron_interchain_txs/src/contract.rs
> +        .debug(format!("WASMDEBUG: sudo: received sud msg: {:?}", msg).as_str());
sud

2022-09-10 21:11 UTC, oopcode commented on contracts/neutron_interchain_txs/src/contract.rs
> +    let resp: MsgSubmitTxResponse = serde_json_wasm::from_slice(
why did you decide to get rid of the parse_sequence() fn here?

2022-09-11 16:53 UTC, pr0n00gler requested changes

2022-09-12 09:35 UTC, foxpy commented on contracts/ibc_transfer/src/contract.rs
> +    .unwrap();
Where is our unwrap-forbidding lint?

2022-09-12 10:51 UTC, foxpy commented on contracts/ibc_transfer/src/contract.rs
> +    .unwrap();
Please add `#![warn(clippy::unwrap_used, clippy::expect_used)]` to `contracts/ibc_transfer/src/lib.rs`

2022-09-12 10:51 UTC, foxpy commented on contracts/neutron_interchain_txs/src/contract.rs
> +        .debug(format!("WASMDEBUG: reply msg: {:?}", resp).as_str());
```suggestion
        .debug(&format!("WASMDEBUG: reply msg: {:?}", resp));
```

2022-09-12 11:02 UTC, foxpy requested changes

2022-09-12 11:02 UTC, foxpy commented on build_proto.sh
> +--rust_out /opt/packages/neutron-sdk/src/ibc/"
Please add `make proto-gen` rule to run this script

2022-09-14 07:37 UTC, foxpy approved these changes

2022-09-14 09:08 UTC, oopcode approved these changes

2022-09-14 09:12 UTC, pr0n00gler approved these changes

2022-09-14 09:13 UTC, merged