feat: sendmsg implemented
neutron-org/neutron-contracts pull request #36
Opened 2022-09-29 14:12 UTC by swelf19

Implemented Send msg, witch submit bank.SendMsg on the remote chain. Required by https://github.com/neutron-org/neutron-activity-scripts/pull/1

2022-10-10 12:58 UTC, NeverHappened submitted a review, later dismissed

2022-10-20 07:48 UTC, NeverHappened approved these changes

2022-10-23 17:16 UTC, foxpy requested changes

2022-10-23 17:16 UTC, foxpy commented on contracts/neutron_interchain_txs/src/contract.rs
> +        .map_err(|_| StdError::generic_err(format!("{} ica not found", key)))?
I would rather use `may_load` there.

2022-11-07 11:03 UTC, pr0n00gler approved these changes

2022-11-07 12:45 UTC, closed without merging