Add sequence id to acknowledgement results key
neutron-org/neutron-contracts pull request #39
Opened 2022-10-12 14:48 UTC by NeverHappened

2022-10-19 10:50 UTC, foxpy requested changes

2022-10-19 10:50 UTC, foxpy commented on contracts/neutron_interchain_txs/src/msg.rs
> +        sequence_id: u64,
This change will break our integration tests suite here: https://github.com/neutron-org/neutron-integration-tests/blob/main/src/testcases/interchaintx.test.ts#L394

Please open updating PR in integration tests as well.

2022-10-20 14:58 UTC, oopcode approved these changes
tested with https://github.com/neutron-org/neutron-integration-tests/pull/21/files, everything's fine; please update the docs and tutorials

2022-10-21 11:29 UTC, quasisamurai commented
test w `feat/introduce-sequence-id` works flawless

2022-10-21 11:30 UTC, quasisamurai approved these changes

2022-10-21 12:15 UTC, swelf19 approved these changes

2022-10-21 12:19 UTC, pr0n00gler approved these changes

2022-10-21 13:07 UTC, merged

2022-10-21 13:09 UTC, albertandrejev commented on contracts/neutron_interchain_txs/src/contract.rs
> +    let keys: Vec<StdResult<(String, u64)>> = ACKNOWLEDGEMENT_RESULTS
You can use `Vec<_>` instead
```suggestion
    let keys: Vec<_> = ACKNOWLEDGEMENT_RESULTS
```